### PR TITLE
Complex.html and Experimental.html fixed

### PR DESCRIPTION
**Pull request by Becker-Asano**
Due to some "some origin" policies in the browser only simple.html worked. The use of the custom random function as a module was a problem in complex.html and experimental.html.
This hack fixes this problem by copying the random.js code directly into complex.js and main.js. This is nice, but it works.

### CODE REVIEW

**Comment by simondevyoutube** [comment]
I'd like to understand what the problem is a bit better, can you explain why this is happening? I've loaded the project in both Chrome & Firefox with no issues.

**Comment by Becker-Asano** [comment]
It is a "same origin" issue. When I open "complex.html" the page remains blank except for the menu on the left side. The developer console shows the following error message:
"Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf file:///C:/Users/Christian/Desktop/test/LSystems_JavaScript-master/src/complex.js. (Grund: CORS-Anfrage war nicht http)."
This is the help page for this error: https://developer.mozilla.org/de/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default

My guess:

- You include complex.js as type=module because..
- complex.js imports "random.js", which is only possible, when complex.js is included as module

My fix is ugly, but works for me.

Why this violates the same origin policy both in firefox and in chrome is strange, though.

I hope this helps.

**Comment by Becker-Asano** [comment]
Wait, I guess I found out why:
I open the file complex.html via file:///.../complex.html and not http(s)://.../complex.html
Thus, the error is thrown, because of the import in complex.js of random.js.

When this is deployed on a web server, the error will not happen, I guess.

**Comment by simondevyoutube** [comment]
That makes sense, this isn't meant to be opened directly in your browser. It has to be hosted, even locally. I use the command:

python3 -m http.server

To serve these locally, others have used nodejs or even a Chrome extension. Since this isn't a bug, I'll close this without merging the change, but thanks for taking the time to look at this.

**Pull request closed without merging**
